### ISSUE TITLE
mark mockito dependency with the test scope in pom.xml

### ISSUE THREAD

**Issue by pgroudas** [sendwithus/sendwithus_java#18]
Its pulling it in as a compile-time release dependency with the current configuration.

**Comment by bvanvugt** [comment]
@pgroudas ah great catch. we'll get that updated :)

**Comment by demoore** [comment]
Hey @pgroudas if you can throw up a small pull request we can get this out sooner, otherwise we'll push out a fix next week. :smile_cat:

**Comment by mariesta** [comment]
Hey @pgroudas, I added the testing scope to the mockito dependency. I am thinking that should fixed your issue. Let me know if you notice anything else.

**Comment by pgroudas** [comment]
Thanks a lot!
