### ISSUE TITLE
1.9.0 client has no method for getting templates with html content

### ISSUE THREAD

**Issue by lenikirilov-taulia** [sendwithus/sendwithus_java#23]
### Client version
1.9.0

### Expected behaviour
Method for getting templates with html content

### Actual behaviour
no such method. only template ids/names

### Steps to reproduce
When do you intend to add such method to the client ?

**Comment by dlsteuer** [comment]
Hey there @lenikirilov-taulia thanks for bringing this to our attention. How does today work for you? #24 Version 1.10.0 is now available with methods for getting the template versions which contains the html.
