### ISSUE TITLE
SendWithUsSendRequest asMap Method Doesn't Put Headers in Request

### ISSUE THREAD

**Issue by dghuang** [sendwithus/sendwithus_java#27]
### Client version
1.10.0

### Expected behaviour
When the SendWithUs send method is called on a SendWithUsSendRequest, the request should send with the headers that were set in the SendWithUsSendRequest object.

### Actual behaviour
Headers aren't changed as a part of SendWithUsSendRequest. Since the send method calls the request's asMap function, and the asMap function doesn't add the request headers to the returned map, the headers aren't sent to the email.

**Comment by demoore** [comment]
Thanks @dghuang! I've just put up a [PR that addresses this](https://github.com/sendwithus/sendwithus_java/pull/28). Hopefully we can get it out and up on maven tomorrow.

**Comment by dghuang** [comment]
Hey @demoore, any updates?

**Comment by demoore** [comment]
It's just been pushed! Pull version 1.11.1 😸 

Thanks @dghuang
