### ISSUE TITLE
Question: When using SendGrid as ESP, how to setup unique arguments for webhook notification?

### ISSUE THREAD

**Issue by tuohope** [sendwithus/sendwithus_java#40]
https://sendgrid.com/docs/API_Reference/SMTP_API/unique_arguments.html

**Comment by demoore** [comment]
Hi @tuohope, can you reach out to our support team: support @ sendwithus.com with some details on what you're trying to do and why.

They can help you once we understand what you're trying to accomplish. Thanks!
