### ISSUE TITLE
Get Mail via log_id

### ISSUE THREAD

**Issue by senolatac** [sendwithus/sendwithus_java#43]
### Client version
2.1.0
### Expected behaviour
Get sent mail or get log message body via log_id
### Actual behaviour
Not provided?
### Steps to reproduce
1. senWithUsAPI.send(...request);
2. get receiptID or logId from response.
3. then use this logId to fetch mail or provide a link to reach mail.

##### Note: reproduce step is expected reproduce steps.

**Comment by senolatac** [comment]
Actually, you provide it on your dashboard. via API?

Request URL: 
https://app.sendwithus.com/ajax/logs/log_id/?action=view_email

Request Method: 
POST

**Comment by demoore** [comment]
@senolatac what are you looking to do? Would adding an endpoint for this method help? [https://support.sendwithus.com/api/#logsapi](https://support.sendwithus.com/api/#logsapi)

**Comment by senolatac** [comment]
I sent a mail like:

<html>
...
<body>
Hello...
</body>
</html>

When I send it via sendwithus, I will have a log_id. With using this log_id, I want to reach this mail content.

https://support.sendwithus.com/api/#logsapi -> this endpoint provides only state but not provide html-body info.

**Comment by demoore** [comment]
Gotcha! This is deliberately a dashboard-only feature. Can you reach out to support team at support[AT]sendwithus.com to discuss your use case? Someone from there will be able to help you out. Thanks!
