### ISSUE TITLE
Unknown error 502, contact api@sendwithus.com

### ISSUE THREAD

**Issue by andron3000** [sendwithus/sendwithus_java#48]
### Client version
com.sendwithus:java-client:1.9.0

### Expected behaviour
email delivered successfully
### Actual behaviour
Unknown error 502, contact api@sendwithus.com

error stack-trace:
`com.sendwithus.exception.SendWithUsException: Unknown error 502, contact api@sendwithus.com 	at com.sendwithus.SendWithUs.makeURLRequest(SendWithUs.java:178) 	at com.sendwithus.SendWithUs.send(SendWithUs.java:491)`

### Steps to reproduce
intermitted issue:
![image](https://user-images.githubusercontent.com/18425328/158205294-d595eaa2-9d78-4e40-8cb4-fede532ef9c3.png)

**Comment by demoore** [comment]
Hey @andron3000, looks like that correlated with some [API related incidents](https://status.sendwithus.com/). Generally, intermittent 5xx errors are safe to retry.
